
/* Code automatically generated by Vult https://github.com/modlfo/vult */
#include "Chicken.h"

void Chicken__ctx_type_1_init(Chicken__ctx_type_1 &_output_){
   Chicken__ctx_type_1 _ctx;
   _ctx.out = 0.0f;
   Chicken__ctx_type_0_init(_ctx._inst2);
   _output_ = _ctx;
   return ;
}


